version: 2

builds:
  - id: kubeconfig-composer
    binary: kubeconfig-composer
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/naymi/kubeconfig-composer/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: install.sh

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  prerelease: auto
  extra_files:
    - glob: install.sh
